default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV['JESSDOCS_POSTGRESS_USER'] %>
  password: <%= ENV['JESS_DOCS_POSTGRESS_PASSWORD'] %>

development:
  <<: *default
  database: jessdocs_development

test:
  <<: *default
  database: jessdocs_test

production:
  <<: *default
  database: jessdocs_production
